// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Tweets = (function(_super) {

    __extends(Tweets, _super);

    function Tweets() {
      return Tweets.__super__.constructor.apply(this, arguments);
    }

    Tweets.prototype.model = Tweet;

    Tweets.prototype.url = "http://api.twitter.com/1/statuses/user_timeline.json?screen_name=davidcornu";

    Tweets.prototype.fetch = function() {
      var _this = this;
      return $.ajax({
        url: this.url,
        method: 'GET',
        dataType: 'JSONP',
        success: function(tweets) {
          var models, tweet, _i, _len;
          models = [];
          for (_i = 0, _len = tweets.length; _i < _len; _i++) {
            tweet = tweets[_i];
            models.push(new Tweet(tweet));
          }
          return _this.reset(models);
        }
      });
    };

    Tweets.prototype.withLinks = function() {
      return this.filter(tweet(function() {}));
    };

    return Tweets;

  })(Backbone.Collection);

}).call(this);
