// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Router = (function(_super) {

    __extends(Router, _super);

    function Router() {
      return Router.__super__.constructor.apply(this, arguments);
    }

    Router.prototype.routes = {
      '': 'login',
      'main': 'main'
    };

    Router.prototype.login = function() {
      var view;
      view = new LoginView;
      return $('#app').html(view.render().el);
    };

    Router.prototype.main = function() {
      var view;
      view = new MainView;
      return $('#app').html(view.render().el);
    };

    return Router;

  })(Backbone.Router);

}).call(this);
