// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.LoginView = (function(_super) {

    __extends(LoginView, _super);

    function LoginView() {
      this.render = __bind(this.render, this);
      return LoginView.__super__.constructor.apply(this, arguments);
    }

    LoginView.prototype.tagName = 'div';

    LoginView.prototype.className = 'login';

    LoginView.prototype.render = function() {
      var template;
      template = $("script#login-template").html();
      this.$el.html(Handlebars.compile(template));
      return this;
    };

    return LoginView;

  })(Backbone.View);

}).call(this);
